name: Calling workflow demonstrating reusable workflows

on: 
  workflow_dispatch

env:
  testvar: from caller

permissions:
  id-token: write
  contents: read

jobs:
  # cf: https://github.com/orgs/community/discussions/26671
  setvars:
    runs-on: ubuntu-latest
    outputs:
      testvar: ${{ env.testvar }}
    steps:      
      - run: echo setting vars

  call-reusable-workflow:
    needs: [setvars]
    uses: ./.github/workflows/reusable-called.yml
    with:
      passed-var: ${{ needs.setvars.outputs.testvar }}
      

