name: Called workflow demonstrating reusable workflows

on: 
  workflow_call:
    inputs:
      passed-var:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: check variable scope
        run: |
          echo testvar: ${{ env.testvar }}
          echo passed-var: ${{ inputs.passed-var }}

